const assert=require('node:assert/strict')
const M=require('../Model.js')
const P=require('../Preferences.js')
const account=(id,appId)=>({id,name:id,appId,enabled:true,browser:'omarchy-launch-webapp',profile:'Work',url:'https://teams.microsoft.com',command:[]})
const definitions=[account('work','teams-work'),account('personal','teams-personal')]
assert.equal(P.accountError(definitions),'')
assert.equal(P.accountError([definitions[0],{...definitions[1],appId:'TEAMS-WORK'}]),'This application ID is already assigned to an account.')
for(const accounts of [null,{},[null],[{...definitions[0],command:'sh -c bad'}],[{...definitions[0],command:['']}],[{...definitions[0],url:'javascript:bad'}],[{...definitions[0],enabled:'true'}],[{...definitions[0],browser:'browser --arg'}]]) assert.notEqual(P.accountError(accounts),'')
assert.deepEqual(P.value({},'accounts'),[])
assert.equal(P.valid('hideWhenClosed','false'),false)
assert.equal(P.valid('__proto__',true),false)
assert.equal(P.language('system','nb_NO'),'nb')
assert.equal(P.text('%1 unread','nb',['$&']),'$& uleste')
assert.deepEqual(M.titleState('(12) Chat | Team | Microsoft Teams'),{unread:12,context:'Chat | Team'})
assert.equal(M.titleState('Chat | Microsoft Teams').unread,0)
for(const title of ['', 'Loading…', 'Sign in | Microsoft Teams', '(99) unrelated', '(9007199254740992) Microsoft Teams']) assert.equal(M.titleState(title).unread,null)
const first={appId:'TEAMS-WORK',title:'(5) Chat | Microsoft Teams',activated:false,toplevel:'one'}
const focused={...first,title:'(3) Chat | Microsoft Teams',activated:true,toplevel:'two'}
let rows=M.accountsForWindows(definitions,[first,focused,{appId:'browser',title:'(99) Microsoft Teams'}])
assert.equal(rows[0].unread,5)
assert.equal(rows[0].toplevel,'two')
assert.equal(rows[1].unread,null)
assert.equal(rows[1].running,false)
assert.deepEqual(M.summary(rows),{totalUnread:5,runningCount:1,unknownCount:1,accountCount:2})
assert.equal(M.primaryAccount(rows,'personal').id,'personal')
assert.equal(M.primaryAccount(rows,'deleted').id,'work')
assert.equal(M.displayedAccounts(rows,false,true).length,1)
assert.equal(M.accountsForWindows([{...definitions[0],enabled:false}], [first]).length,0)
assert.equal(M.candidates([first,focused]).length,1)
assert.deepEqual(M.launchArguments(definitions[0]),['omarchy-launch-webapp','https://teams.microsoft.com','--profile-directory=Work'])
assert.deepEqual(M.launchArguments({...definitions[0],browser:'chromium',profile:''}),['chromium','--app=https://teams.microsoft.com'])
assert.deepEqual(M.launchArguments({...definitions[0],command:['client','$(touch nope)']}),['client','$(touch nope)'])
console.log('Teams model, configuration, matching, deduplication and argv tests passed')
